<template>
    <MasterlistTemp
        :pageTitle="'Baranagay Aurora Masterlist, Compostela, Davao de Oro'"
        :tableHeaders="tableHeaders"
        :tableData="tableData"
    />
</template>

<script setup lang="ts">
import MasterlistTemp from "@/Layouts/MasterlistTemp.vue";
import { ref } from "vue";

const tableHeaders = [
    "No.",
    "Last Name",
    "First Name",
    "Barangay",
    "Purok",
    "Amount",
    "Status",
];

const tableData = ref([
    {
        no: 1,
        lastName: "Potter",
        firstName: "Harry",
        barangay: "Gryffindor",
        purok: "7th",
        status: "Claimed",
        amount: "7,000",
    },
    {
        no: 2,
        lastName: "Granger",
        firstName: "Hermione",
        barangay: "Gryffindor",
        purok: "7th",
        amount: "8,500",
        status: "Claimed",
    },
    {
        no: 3,
        lastName: "Weasley",
        firstName: "Ron",
        barangay: "Gryffindor",
        purok: "7th",
        amount: "5,500",
        status: "Claimed",
    },
    {
        no: 4,
        lastName: "Malfoy",
        firstName: "Draco",
        barangay: "Slytherin",
        purok: "7th",
        amount: "10,000",
        status: "Claimed",
    },
    {
        no: 5,
        lastName: "Longbottom",
        firstName: "Neville",
        barangay: "Gryffindor",
        purok: "7th",
        amount: "6,000",
        status: "Claimed",
    },
    {
        no: 6,
        lastName: "Lovegood",
        firstName: "Luna",
        barangay: "Ravenclaw",
        purok: "6th",
        amount: "7,500",
        status: "Pending",
    },
    {
        no: 7,
        lastName: "Weasley",
        firstName: "Ginny",
        barangay: "Gryffindor",
        purok: "6th",
        amount: "6,500",
        status: "Claimed",
    },
    {
        no: 8,
        lastName: "Diggory",
        firstName: "Cedric",
        barangay: "Hufflepuff",
        purok: "7th",
        amount: "9,000",
        status: "Disqualified",
    },
    {
        no: 9,
        lastName: "Chang",
        firstName: "Cho",
        barangay: "Ravenclaw",
        purok: "7th",
        amount: "7,800",
        status: "Pending",
    },
    {
        no: 10,
        lastName: "Finnigan",
        firstName: "Seamus",
        barangay: "Gryffindor",
        purok: "7th",
        amount: "6,200",
        status: "Claimed",
    },
    {
        no: 11,
        lastName: "Thomas",
        firstName: "Dean",
        barangay: "Gryffindor",
        purok: "7th",
        amount: "6,300",
        status: "Pending",
    },
    {
        no: 12,
        lastName: "Brown",
        firstName: "Lavender",
        barangay: "Gryffindor",
        purok: "7th",
        amount: "5,900",
        status: "Disqualified",
    },
    {
        no: 13,
        lastName: "Patil",
        firstName: "Parvati",
        barangay: "Gryffindor",
        purok: "7th",
        amount: "6,100",
        status: "Claimed",
    },
    {
        no: 14,
        lastName: "Patil",
        firstName: "Padma",
        barangay: "Ravenclaw",
        purok: "7th",
        amount: "6,100",
        status: "Pending",
    },
    {
        no: 15,
        lastName: "Zabini",
        firstName: "Blaise",
        barangay: "Slytherin",
        purok: "7th",
        amount: "9,500",
        status: "Claimed",
    },
    {
        no: 16,
        lastName: "Parkinson",
        firstName: "Pansy",
        barangay: "Slytherin",
        purok: "7th",
        amount: "8,200",
        status: "Claimed",
    },
    {
        no: 17,
        lastName: "Bones",
        firstName: "Susan",
        barangay: "Hufflepuff",
        purok: "7th",
        amount: "6,700",
        status: "Claimed",
    },
    {
        no: 18,
        lastName: "Abbott",
        firstName: "Hannah",
        barangay: "Hufflepuff",
        purok: "7th",
        amount: "6,600",
        status: "Pending",
    },
    {
        no: 19,
        lastName: "Macmillan",
        firstName: "Ernie",
        barangay: "Hufflepuff",
        purok: "7th",
        amount: "7,100",
        status: "Claimed",
    },
    {
        no: 20,
        lastName: "Goldstein",
        firstName: "Anthony",
        barangay: "Ravenclaw",
        purok: "7th",
        amount: "7,300",
        status: "Claimed",
    },
    {
        no: 21,
        lastName: "Boot",
        firstName: "Terry",
        barangay: "Ravenclaw",
        purok: "7th",
        amount: "7,200",
        status: "Claimed",
    },
    {
        no: 22,
        lastName: "Corner",
        firstName: "Michael",
        barangay: "Ravenclaw",
        purok: "7th",
        amount: "7,000",
        status: "Pending",
    },
    {
        no: 23,
        lastName: "Crabbe",
        firstName: "Vincent",
        barangay: "Slytherin",
        purok: "7th",
        amount: "5,800",
        status: "Disqualified",
    },
    {
        no: 24,
        lastName: "Goyle",
        firstName: "Gregory",
        barangay: "Slytherin",
        purok: "7th",
        amount: "5,700",
        status: "Disqualified",
    },
    {
        no: 25,
        lastName: "Greengrass",
        firstName: "Daphne",
        barangay: "Slytherin",
        purok: "7th",
        amount: "8,800",
        status: "Claimed",
    },
    {
        no: 26,
        lastName: "Nott",
        firstName: "Theodore",
        barangay: "Slytherin",
        purok: "7th",
        amount: "9,200",
        status: "Claimed",
    },
    {
        no: 27,
        lastName: "Bulstrode",
        firstName: "Millicent",
        barangay: "Slytherin",
        purok: "7th",
        amount: "7,600",
        status: "Pending",
    },
    {
        no: 28,
        lastName: "Creevey",
        firstName: "Colin",
        barangay: "Gryffindor",
        purok: "6th",
        amount: "5,500",
        status: "Disqualified",
    },
    {
        no: 29,
        lastName: "Bell",
        firstName: "Katie",
        barangay: "Gryffindor",
        purok: "7th",
        amount: "6,900",
        status: "Claimed",
    },
    {
        no: 30,
        lastName: "Jordan",
        firstName: "Lee",
        barangay: "Gryffindor",
        purok: "7th",
        amount: "6,800",
        status: "Pending",
    },
]);
</script>
